services:
  - type: web
    name: colorcompete
    env: node
    plan: free
    buildCommand: npm install --include=dev && cd client && npx vite build && cd .. && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: colorcompete-db
          property: connectionString
    domains:
      - colorcompete.com
      - www.colorcompete.com

databases:
  - name: colorcompete-db
    databaseName: colorcompete
    user: colorcompete_user
    plan: free